// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigMigrationItem } from "./ExternalAgentConfigMigrationItem";

export type ExternalAgentConfigImportParams = { migrationItems: Array<ExternalAgentConfigMigrationItem>,
/**
 * Import-source selector used to produce the migration items. Pass the same value to detection
 * and import; missing or unrecognized values use the default source for backwards
 * compatibility.
 */
source?: string | null, };
