// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigImportTypeResult } from "./ExternalAgentConfigImportTypeResult";

export type ExternalAgentConfigImportHistoryRecordParams = {
/**
 * Opaque provider identifier for the externally completed import.
 */
providerId: string,
/**
 * Completed results grouped by imported item type.
 */
itemTypeResults: Array<ExternalAgentConfigImportTypeResult>, };
